# Generated by Django 4.1.1 on 2022-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAdmin', '0002_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
