# Generated by Django 4.1.1 on 2022-10-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAdmin', '0003_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='pan',
        ),
    ]
